package releasegate

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"sort"
	"strings"
	"sync"

	"code.byted.org/data-arch/ovtest/ops"
)

type Outcome struct {
	Primary error
	Cleanup error
}

func (o Outcome) Err() error {
	return errors.Join(o.Primary, o.Cleanup)
}

type OwnershipRegistry struct {
	runID string
	mu    sync.Mutex
	owned map[string]struct{}
}

func NewOwnershipRegistry(runID string) *OwnershipRegistry {
	return &OwnershipRegistry{runID: runID, owned: map[string]struct{}{}}
}

func (r *OwnershipRegistry) Own(rawURI string) error {
	return r.own(rawURI, true)
}

// OwnGenerated records a concrete leaf URI returned by a successful create
// operation. The capability comes from that structured result, so generated IDs
// do not need to embed the run ID.
func (r *OwnershipRegistry) OwnGenerated(rawURI string) error {
	return r.own(rawURI, false)
}

// Claim records cleanup authority produced by a successful typed operation.
// The registry validates the exact URI shape again at the deletion boundary.
func (r *OwnershipRegistry) Claim(claim ops.CleanupClaim) error {
	if strings.TrimSpace(claim.Source) == "" || strings.TrimSpace(claim.Proof) == "" {
		return fmt.Errorf("cleanup ownership: claim source and proof are required")
	}
	uri, err := parseClaimURI(claim.URI)
	if err != nil {
		return err
	}
	segments := strings.FieldsFunc(uri.EscapedPath(), func(r rune) bool { return r == '/' })
	switch claim.Kind {
	case "session":
		legacy := uri.Host == "session" && len(segments) == 1
		canonical := uri.Host == "user" && len(segments) == 3 && segments[1] == "sessions"
		if !legacy && !canonical {
			return fmt.Errorf("cleanup ownership: invalid session claim %q", claim.URI)
		}
	case "memory":
		if !ops.ValidCleanupClaimURI(claim.URI, "memory") {
			return fmt.Errorf("cleanup ownership: invalid memory claim %q", claim.URI)
		}
	case "resource":
		if uri.Host != "resources" || len(segments) < 2 {
			return fmt.Errorf("cleanup ownership: invalid resource claim %q", claim.URI)
		}
	default:
		return fmt.Errorf("cleanup ownership: unsupported claim kind %q", claim.Kind)
	}
	for _, segment := range segments {
		decoded, decodeErr := url.PathUnescape(segment)
		if decodeErr != nil || decoded == "" || decoded == "." || decoded == ".." || strings.Contains(decoded, "/") {
			return fmt.Errorf("cleanup ownership: invalid escaped path %q", claim.URI)
		}
		if claim.Kind == "session" && !safeName.MatchString(decoded) {
			return fmt.Errorf("cleanup ownership: invalid session ID %q", claim.URI)
		}
	}
	r.record(claim.URI)
	return nil
}

func parseClaimURI(rawURI string) (*url.URL, error) {
	uri, err := url.Parse(rawURI)
	if err != nil || uri.Scheme != "viking" || uri.Host == "" || uri.RawQuery != "" || uri.Fragment != "" || uri.User != nil {
		return nil, fmt.Errorf("cleanup ownership: invalid Viking URI %q", rawURI)
	}
	return uri, nil
}

func (r *OwnershipRegistry) record(rawURI string) {
	normalized := strings.TrimRight(rawURI, "/")
	r.mu.Lock()
	r.owned[normalized] = struct{}{}
	r.mu.Unlock()
}

func (r *OwnershipRegistry) own(rawURI string, requireRunID bool) error {
	if r == nil || !safeName.MatchString(r.runID) {
		return fmt.Errorf("cleanup ownership: safe run ID is required")
	}
	uri, err := url.Parse(rawURI)
	if err != nil || uri.Scheme != "viking" || uri.Host == "" || uri.RawQuery != "" || uri.Fragment != "" {
		return fmt.Errorf("cleanup ownership: invalid Viking URI %q", rawURI)
	}
	segments := strings.FieldsFunc(uri.EscapedPath(), func(r rune) bool { return r == '/' })
	if uri.Host == "session" {
		// Session IDs are generated by the isolated harness invocation and are
		// registered from its structured output. Only the exact session root is
		// accepted; the namespace root and arbitrary descendants remain unsafe.
		if requireRunID || len(segments) != 1 {
			return fmt.Errorf("cleanup ownership: broad or unverified session URI rejected %q", rawURI)
		}
	} else if len(segments) < 2 || (uri.Host != "user" && uri.Host != "resources" && uri.Host != "agent") {
		return fmt.Errorf("cleanup ownership: broad URI rejected %q", rawURI)
	}
	owned := false
	for _, segment := range segments {
		decoded, decodeErr := url.PathUnescape(segment)
		if decodeErr != nil {
			return fmt.Errorf("cleanup ownership: invalid escaped path %q", rawURI)
		}
		if uri.Host == "session" && !safeName.MatchString(decoded) {
			return fmt.Errorf("cleanup ownership: invalid session ID %q", rawURI)
		}
		if decoded == r.runID {
			owned = true
		}
	}
	if requireRunID && !owned {
		return fmt.Errorf("cleanup ownership: URI does not contain run ID %q", rawURI)
	}
	if !requireRunID && (uri.Host == "user" || uri.Host == "agent") && !ops.ValidCleanupClaimURI(rawURI, "memory") {
		return fmt.Errorf("cleanup ownership: generated user URI is not a memory leaf %q", rawURI)
	}
	r.record(rawURI)
	return nil
}

func (r *OwnershipRegistry) URIs() []string {
	if r == nil {
		return nil
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	out := make([]string, 0, len(r.owned))
	for uri := range r.owned {
		out = append(out, uri)
	}
	sort.Sort(sort.Reverse(sort.StringSlice(out)))
	return out
}

func (r *OwnershipRegistry) Cleanup(ctx context.Context, primary error, deleteURI func(context.Context, string) error) Outcome {
	if ctx == nil {
		ctx = context.Background()
	}
	if deleteURI == nil {
		return Outcome{Primary: primary, Cleanup: fmt.Errorf("cleanup: nil delete function")}
	}
	var cleanup []error
	for _, uri := range r.URIs() {
		if err := deleteURI(ctx, uri); err != nil {
			cleanup = append(cleanup, fmt.Errorf("delete %s: %w", uri, err))
		}
	}
	return Outcome{Primary: primary, Cleanup: errors.Join(cleanup...)}
}
